---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-1
  labels:
    role: zookeeper
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    role: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-2
  labels:
    role: zookeeper
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    role: zookeeper
