---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zookeeper-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: zookeeper
    spec:
      containers:
      - name: zookeeper-1
        image: digitalwonderland/zookeeper
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: zookeeper-1.default.svc.cluster.local
        - name: ZOOKEEPER_SERVER_2
          value: zookeeper-2.default.svc.cluster.local
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zookeeper-2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: zookeeper
    spec:
      containers:
      - name: zookeeper-2
        image: digitalwonderland/zookeeper
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        env:
        - name: ZOOKEEPER_ID
          value: "2"
        - name: ZOOKEEPER_SERVER_1
          value: zookeeper-1.default.svc.cluster.local
        - name: ZOOKEEPER_SERVER_2
          value: zookeeper-2.default.svc.cluster.local
---
