---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zookeeper-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: zookeeper
    spec:
      containers:
      - name: zookeeper-1
        image: us.gcr.io/fcuny-devel/zookeeper
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        env:
        - name: zk_id
          value: "1"
        - name: SERVERS
          value: zookeeper-2.default.svc.cluster.local
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zookeeper-2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: zookeeper
    spec:
      containers:
      - name: zookeeper-2
        image: us.gcr.io/fcuny-devel/zookeeper
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        env:
        - name: zk_id
          value: "2"
        - name: SERVERS
          value: zookeeper-1.default.svc.cluster.local
---
